name: Compile and Release AHK Script

on:
  push:
    tags:
      - 'v*'  
  workflow_dispatch:
  
jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile AHK to EXE
      uses: nekocodeX/GitHub-Action-Ahk2Exe@main
      with:
        in: main.ahk  

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: main.exe  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
